//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airport_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Airplane
    {
        [Required]
        [DataType(DataType.Text)]
        public string Model_No { get; set; }
        [Required]
        [DataType(DataType.Text)]
        public string Capacity { get; set; }
        [Required]
        [DataType(DataType.Text)]
        public string Fuel_Capacity { get; set; }
        [Required]
        [DataType(DataType.Text)]
        public string Airline_Name { get; set; }
    
        public virtual Airline Airline { get; set; }
    }
}
