//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airport_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Boarding
    {
        [Required]
        [DataType(DataType.Text)]
        public string Boarding_ID { get; set; }
        [Required]
        [DataType(DataType.DateTime)]
        public string Time { get; set; }
        [Required]
        [DataType(DataType.Text)]
        public string Schedule_No { get; set; }
        [Required]
        [DataType(DataType.Text)]
        public string Gate_No { get; set; }
    
        public virtual Gate Gate { get; set; }
        public virtual Schedule Schedule { get; set; }
    }
}
