//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airport_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Employee_Passenger = new HashSet<Employee_Passenger>();
        }

        [Required]
        [DataType(DataType.Text)]
        public string Emp_ID { get; set; }
        [Required]
        [DataType(DataType.Text)]
        public string Name { get; set; }
        [Required]
        [DataType(DataType.Date)]
        public string DOB { get; set; }
        [Required]
        [DataType(DataType.Text)]
        public string Designation { get; set; }
        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        [Required]
        [DataType(DataType.Text)]
        public string Gender { get; set; }
        [Required]
        [DataType(DataType.Text)]
        public string H_no { get; set; }
        [Required]
        [DataType(DataType.Text)]
        public string Area { get; set; }
        [Required]
        [DataType(DataType.Text)]
        public string City { get; set; }
        [Required]
        [DataType(DataType.Text)]
        public string Country { get; set; }
        [Required]
        [DataType(DataType.Text)]
        public string Salary { get; set; }
        [Required]
        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"^\+\d{2}-\d{3}-\d{7}$", ErrorMessage = "Invalid phone number format. Use +XX-XXX-XXXXXXX.")]
        public string Phone_No { get; set; }
        [Required]
        [DataType(DataType.EmailAddress)]
        [RegularExpression(@"^[^\s@]+@[^\s@]+\.[^\s@]+$", ErrorMessage = "Invalid email address format.")]
        public string Email { get; set; }
        [Required]
        [DataType(DataType.Text)]
        public string Airport_Name { get; set; }
    
        public virtual Airport Airport { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee_Passenger> Employee_Passenger { get; set; }
    }
}
