//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airport_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Flight
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Flight()
        {
            this.Luggages = new HashSet<Luggage>();
            this.Passengers = new HashSet<Passenger>();
            this.Tickets = new HashSet<Ticket>();
        }

        [Required]
        [DataType(DataType.Text)]
        public string Flight_ID { get; set; }
        [Required]
        [DataType(DataType.DateTime)]
        public string Departure { get; set; }
        [Required]
        [DataType(DataType.DateTime)]
        public string Arrival { get; set; }
        [Required]
        [DataType(DataType.Text)]
        public string Source { get; set; }
        [Required]
        [DataType(DataType.Text)]
        public string Destination { get; set; }
        [Required]
        [DataType(DataType.Text)]
        public string Schedule_No { get; set; }
    
        public virtual Schedule Schedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Luggage> Luggages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Passenger> Passengers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket> Tickets { get; set; }
    }
}
