//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airport_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Ticket
    {
        [Required]
        [DataType(DataType.Text)]
        public string Ticket_No { get; set; }
        [Required]
        [DataType(DataType.Text)]
        public string CNIC { get; set; }
        [Required]
        [DataType(DataType.Text)]
        public string Flight_ID { get; set; }
    
        public virtual Flight Flight { get; set; }
        public virtual Passenger Passenger { get; set; }
    }
}
